### ISSUE TITLE
xQueue usage

### ISSUE THREAD

**Issue by j105** [HomeACcessoryKid/ESP8266-HomeKit#22]
Hi Thanks for such great firmware.

Just wondered that any particular reason that you are using queue system?

It increases complex and causing race conditions issue. Sometimes I am not able to pair due to packet sent before lock being removed.

Cheers
Jimmy Fan

**Comment by HomeACcessoryKid** [comment]
Hi,

Originally I wrote the software without the queue system. It seemed to work but over the course of a day, it would 100% sure crash. I found out because after boot I set the value of the dimmer to some percentage not zero. But at the end of the day it was at zero.

I found that the reference to the socket became stale and this caused the crash. I now will never delete the socket until the pending answer to a question has been calculated. If stale, I do not send the answer. Only if no questions are outstanding the socket can be deleted.

It seems elaborate and if you see a better approach, I'm happy to consider that. But do remember this is RTOS, you often have to delegate to a task, and that task must be able to complete.

I hope this helps, if not, ask in more detail...  
Hack

PS. I suspect that this mechanism interferes with the TCP keep alive cleanup, issue #13
